#ifndef _LITEPOINTIQGIGIFBOX__GLOBAL_H
#define _LITEPOINTIQGIGIFBOX__GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(_LITEPOINTIQGIGIFBOX__LIBRARY)
#  define _LITEPOINTIQGIGIFBOX__EXPORT Q_DECL_EXPORT
#else
#  define _LITEPOINTIQGIGIFBOX__EXPORT Q_DECL_IMPORT
#endif

#endif // _LITEPOINTIQGIGIFBOX__GLOBAL_H
