start _chatapi_.bat
start _csvdataapi_.bat
start _demoapi_.bat
start _fsmpegapi_.bat
start _gameapi_.bat
start _geminiapi_.bat
start _relayapi_.bat
start _ledanalyserapi_.bat
start _litepointiqgigifapi_.bat
start _richerapi_.bat
start _scannerapi_.bat
start _serialportapi_.bat
start _superapi_.bat
start _tcpclientapi_.bat
start _tcpserverapi_.bat
start _wasapiapi_.bat
start _wavdataapi_.bat