cp -r SuperTools-Source/__api__/__supercore__ SuperTools-Source/__plugins__/__device__/_fsmpegbox_
cp -r SuperTools-Source/__api__/__supercodec__ SuperTools-Source/__plugins__/__device__/_fsmpegbox_
cp -r SuperTools-Source/__api__/__supermultimedia__ SuperTools-Source/__plugins__/__device__/_fsmpegbox_
cp -r SuperTools-Source/__api__/__superprogressbardialog__ SuperTools-Source/__plugins__/__device__/_fsmpegbox_
cp -r SuperTools-Source/__api__/__superwindow__ SuperTools-Source/__plugins__/__device__/_fsmpegbox_
cp -r SuperTools-Source/__api__/__supernotedialog__ SuperTools-Source/__plugins__/__device__/_fsmpegbox_
cp -r SuperTools-Source/__api__/__superfiledialog__ SuperTools-Source/__plugins__/__device__/_fsmpegbox_
cp -r SuperTools-Source/__api__/__superflac__ SuperTools-Source/__plugins__/__device__/_fsmpegbox_
cp -r SuperTools-Source/__api__/__supermp3__ SuperTools-Source/__plugins__/__device__/_fsmpegbox_
cp -r SuperTools-Source/__api__/__superape__ SuperTools-Source/__plugins__/__device__/_fsmpegbox_
cp -r SuperTools-Source/__api__/__superlogger__ SuperTools-Source/__plugins__/__device__/_fsmpegbox_
cp -r SuperTools-Source/__api__/__superfilemanager__ SuperTools-Source/__plugins__/__device__/_fsmpegbox_
cp -r SuperTools-Source/__api__/__supertab__ SuperTools-Source/__plugins__/__device__/_fsmpegbox_
cp -r SuperTools-Source/__api__/__supergroupbox__ SuperTools-Source/__plugins__/__device__/_fsmpegbox_
