cp -r SuperTools-Source/__api__/__supercore__ SuperTools-Source/__plugins__/__device__/_richerbox_
cp -r SuperTools-Source/__api__/__superwindow__ SuperTools-Source/__plugins__/__device__/_richerbox_
cp -r SuperTools-Source/__api__/__supernotedialog__ SuperTools-Source/__plugins__/__device__/_richerbox__
cp -r SuperTools-Source/__api__/__superfiledialog__ SuperTools-Source/__plugins__/__device__/_richerbox_
cp -r SuperTools-Source/__api__/__superfinddialog__ SuperTools-Source/__plugins__/__device__/_richerbox_
cp -r SuperTools-Source/__api__/__superfontdialog__ SuperTools-Source/__plugins__/__device__/_richerbox_
cp -r SuperTools-Source/__api__/__superlogger__ SuperTools-Source/__plugins__/__device__/_richerbox_
cp -r SuperTools-Source/__api__/__supercolordialog__ SuperTools-Source/__plugins__/__device__/_richerbox_
cp -r SuperTools-Source/__api__/__superfilemanager__ SuperTools-Source/__plugins__/__device__/_richerbox_
cp -r SuperTools-Source/__api__/__supergroupbox__ SuperTools-Source/__plugins__/__device__/_richerbox_
cp -r SuperTools-Source/__api__/__supertab__ SuperTools-Source/__plugins__/__device__/_richerbox_
