cp -r SuperTools-Source/__api__/__supercore__ SuperTools-Source/__plugins__/__device__/_wavdatabox_
cp -r SuperTools-Source/__api__/__supermultimedia__ SuperTools-Source/__plugins__/__device__/_wavdatabox_
cp -r SuperTools-Source/__api__/__superplot__ SuperTools-Source/__plugins__/__device__/_wavdatabox_
cp -r SuperTools-Source/__api__/__superprogressbardialog__ SuperTools-Source/__plugins__/__device__/_wavdatabox_
cp -r SuperTools-Source/__api__/__superwindow__ SuperTools-Source/__plugins__/__device__/_wavdatabox_
cp -r SuperTools-Source/__api__/__supernotedialog__ SuperTools-Source/__plugins__/__device__/_wavdatabox_
cp -r SuperTools-Source/__api__/__superfiledialog__ SuperTools-Source/__plugins__/__device__/_wavdatabox_
cp -r SuperTools-Source/__api__/__superfftw__ SuperTools-Source/__plugins__/__device__/_wavdatabox_
cp -r SuperTools-Source/__api__/__superlogger__ SuperTools-Source/__plugins__/__device__/_wavdatabox_
cp -r SuperTools-Source/__api__/__superfilemanager__ SuperTools-Source/__plugins__/__device__/_wavdatabox_
cp -r SuperTools-Source/__api__/__superhook__ SuperTools-Source/__plugins__/__device__/_wavdatabox_
cp -r SuperTools-Source/__api__/__supergroupbox__ SuperTools-Source/__plugins__/__device__/_wavdatabox_
cp -r SuperTools-Source/__api__/__supertab__ SuperTools-Source/__plugins__/__device__/_wavdatabox_
